version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: adminpjeczperseo
      POSTGRES_PASSWORD: developPasswd
      POSTGRES_DB: pjecz_perseo
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn -w 2 appserver:gunicorn_app
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      DEPLOYMENT_ENVIRONMENT: develop
      HOST: http://localhost:5000
      PYTHONPATH: /code
      REDIS_URL: redis://redis:6379
      SALT: r5npOyY2519ph2zK
      SECRET_KEY: PvwV7heFDcfrsWFAGxBz2aOvJ1Mw6LgV
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://adminpjeczperseo:developPasswd@db:5432/pjecz_perseo
      TASK_QUEUE: pjecz_perseo

volumes:
  db-data:
